-- DDL generated by Postico 2.0.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "column" (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ns text,
    "column.name" text,
    "column.description" text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX column_pkey ON "column"(id int4_ops);
