-- DDL generated by Postico 2.0.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE info (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone NOT NULL,
    created_by uuid,
    updated_at timestamp without time zone,
    updated_by uuid,
    deleted_at timestamp without time zone,
    deleted_by uuid
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX info_pkey ON info(id int4_ops);
