-- DDL generated by Postico 2.0.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE schema (
    id uuid PRIMARY KEY,
    ns text,
    "schema.name" text,
    "schema.description" text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX schema_pkey ON schema(id uuid_ops);
