name: NodeJS-CI-Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Setup PostgreSQL database
      uses: harmon758/postgreSQL-action@v1
      with:
        postgresql version: '12'

    - name: Start PostgreSQL
      run: sudo service postgresql start        
    
    - name: Set NODE_ENV to CI
      run: echo "NODE_ENV=CI" >> $GITHUB_ENV

    - name: Build
      run: |
        npm install
        npm install -D typescript
        npm test